name: keep cronjobs alive
on:
  schedule:
    - cron: "0 5 * * *"
  tag:

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
