name: Appointment Manager

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    environment: run-appointment-manager-env

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        working-directory: WPAppointmentManager
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Run
        working-directory: WPAppointmentManager
        run: python main.py
        env:
          COUCHDB_HOST: ${{ secrets.COUCHDB_HOST }}
          COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
          COUCHDB_USER: ${{ secrets.COUCHDB_USER }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          WC_URL: ${{ secrets.WC_URL }}
          WC_KEY: ${{ secrets.WC_KEY }}
          WC_SECRET: ${{ secrets.WC_SECRET }}
