name: New Member Mail

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: run-appointment-manager-env

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('NewCustomerManager/requirements.txt') }}
      - name: Install dependencies
        working-directory: NewCustomerManager
        run: pip install -r requirements.txt
      - name: Run
        run: python NewCustomerManager/main.py
        env:
          COUCHDB_HOST: ${{ secrets.COUCHDB_HOST }}
          COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
          COUCHDB_USER: ${{ secrets.COUCHDB_USER }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
